metadataId: 041f1e6e-bdbc-4091-b48f-8a5990f3cc5b
output_directory: produktspesifikasjon
product_slug: admenheter3
updated: 2025-01-01
xmi_url: https://sosi.geonorge.no/svn/SOSI/SOSI Del 3/Statens kartverk/AdministrativeEnheter_FylkerOgKommuner-20240101.xml
